#!/usr/bin/env python3
"""Rebuild a feedback dir's INDEX.md — one section per report with its numbered
proposal titles — so an `extends`-lookup during capture (tool-feedback) or triage
(feedback-triage) is one Read instead of N speculative, phrasing-fragile greps (the
recurrence-grep robustness fix). Stdlib only; best-effort parsing of the report
template's "## Proposed promotions" section. The output (INDEX.md) is a generated
artifact — regenerate it, do not hand-edit.

    uv run --no-project python build_feedback_index.py <feedback-dir>

Use `uv run --no-project python` (not a bare `python` / `python3`): on Windows
without Python on PATH, both resolve to the Microsoft-Store app-execution stub
and abort.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_PROPOSAL = re.compile(r'^\s*(\d+)\.\s+(.+?)\s*$')
_SEVERITY = re.compile(r'\*\*\[[A-Za-z/]+\]\*\*\s*')  # a leading **[MED]** / **[HIGH]** tag


def extract_proposals(text: str) -> list[tuple[str, str]]:
    """Return [(number, title)] from the report's "## Proposed promotions" section.
    The title is stripped of a leading severity tag and capped; parsing stops at the
    next `## ` heading. Best-effort: a report without the section yields []."""
    out: list[tuple[str, str]] = []
    in_section = False
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith('## '):
            in_section = stripped[3:].strip().lower().startswith('proposed')
            continue
        if in_section:
            m = _PROPOSAL.match(line)
            if m:
                title = _SEVERITY.sub('', m.group(2)).strip()
                out.append((m.group(1), title[:140]))
    return out


def _is_report(p: Path) -> bool:
    """A source report — not the index/readme, and not a triage doc or digest
    (those are outputs of the loop, not inputs to index)."""
    name = p.name.lower()
    return (
        p.suffix == '.md'
        and name not in ('index.md', 'readme.md')
        and 'triage' not in name
        and 'digest' not in name
    )


def build_index(feedback_dir: Path) -> str:
    reports = sorted(p for p in feedback_dir.glob('*.md') if _is_report(p))
    lines = [
        '# Feedback index',
        '',
        f'{len(reports)} report(s) — generated by `build_feedback_index.py <dir>`; '
        'do not hand-edit. Each entry is a report stem and its numbered proposals; '
        'grep here for an `extends` target before restating a finding.',
        '',
    ]
    for p in reports:
        lines.append(f'## {p.stem}')
        try:
            props = extract_proposals(p.read_text(encoding='utf-8', errors='replace'))
        except OSError:
            lines += ['- (unreadable)', '']
            continue
        if props:
            lines += [f'- `{p.stem}#{num}` — {title}' for num, title in props]
        else:
            lines.append('- (no numbered proposals)')
        lines.append('')
    return '\n'.join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if not argv:
        print('usage: build_feedback_index.py <feedback-dir>')
        return 2
    d = Path(argv[0])
    if not d.is_dir():
        print(f'not a directory: {d}')
        return 1
    out = d / 'INDEX.md'
    out.write_text(build_index(d), encoding='utf-8')
    print(f'wrote {out}')  # the index header carries the report count
    return 0


if __name__ == '__main__':
    sys.exit(main())
