#!/usr/bin/env python3
"""Generate the repo-root AGENTS.md — the universal discovery index (ADR-0002).

Walks `plugins/*/skills/*/SKILL.md`, `plugins/*/commands/*.md`, and
`plugins/*/output-styles/*.md` and emits one line per artifact — name, trigger
description from frontmatter, repo-relative path — grouped by plugin, behind a
compact dispatch preamble. The output is deterministic (stable ordering, no
timestamps), carries no trailing whitespace, and ends with exactly one newline,
so the pre-commit hygiene fixers and the freshness gate never fight over bytes.

    python scripts/gen_agents_md.py           # (re)write AGENTS.md
    python scripts/gen_agents_md.py --check   # exit 1 if AGENTS.md is stale

AGENTS.md is a derived artifact (ADR-0001): never hand-edit it — change the
frontmatter it renders from and re-run this generator. The frontmatter parser
is reused from the toolkit-awareness plugin (single-sourced there because the
plugin must stay standalone when installed); loaded by file path via importlib.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'AGENTS.md'
PLUGINS = ROOT / 'plugins'
_SCAN_TOOLKIT = (
    PLUGINS / 'session-workflow' / 'skills' / 'toolkit-awareness' / 'scripts' / 'scan_toolkit.py'
)

BANNER = (
    '<!-- GENERATED by scripts/gen_agents_md.py -- do not hand-edit. '
    'Regenerate: uv run --no-project -- python scripts/gen_agents_md.py -->'
)

PREAMBLE = """# craft-collection — agent toolkit index

Skills for any agent that can read files. Each entry below is a trigger
surface: a name, when to use it, and the path of the full skill body. Loading
a skill means reading its `SKILL.md` (and only the `references/` files it
points you at) — nothing here requires a specific harness. On Claude Code the
same skills install as plugins via the marketplace instead (see `README.md`).

Dispatch protocol (the compact form of humblepowers' `choosing-tools`):

- At a task start or direction change, name the task in one phrase and rank
  the entries below by how well their description fits it.
- Load a skill body only when its expected benefit clearly exceeds its context
  cost; load at most one process discipline at a time.
- When nothing clearly fits, proceed without loading — "no skill owns this" is
  a correct outcome.
- Set aside a loaded skill that turns out not to fit, explicitly."""


def _load_read_frontmatter():
    """Import `_read_frontmatter` from the plugin's scan_toolkit.py by path."""
    spec = importlib.util.spec_from_file_location('scan_toolkit', _SCAN_TOOLKIT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._read_frontmatter


def _plugin_description(plugin_dir: Path) -> str:
    try:
        data = json.loads(
            (plugin_dir / '.claude-plugin' / 'plugin.json').read_text(encoding='utf-8')
        )
    except (OSError, json.JSONDecodeError, ValueError):
        return ''
    return str(data.get('description', '')) if isinstance(data, dict) else ''


def _entry(name: str, description: str, path: Path) -> str:
    desc = ' '.join(description.split()) or '(no description)'
    return f'- **{name}** — {desc} (`{path.relative_to(ROOT).as_posix()}`)'


def render() -> str:
    """Render the full AGENTS.md content, deterministically."""
    read_frontmatter = _load_read_frontmatter()
    lines: list[str] = [BANNER, '', PREAMBLE, '']
    for plugin_dir in sorted(p for p in PLUGINS.iterdir() if p.is_dir()):
        lines += [f'## {plugin_dir.name}', '']
        pdesc = _plugin_description(plugin_dir)
        if pdesc:
            lines += [' '.join(pdesc.split()), '']
        skills = sorted((plugin_dir / 'skills').glob('*/SKILL.md'))
        if skills:
            lines.append('### Skills')
            for md in skills:
                fm = read_frontmatter(md)
                lines.append(_entry(fm.get('name', md.parent.name), fm.get('description', ''), md))
            lines.append('')
        for kind, sub in (('Commands', 'commands'), ('Output styles', 'output-styles')):
            found = sorted((plugin_dir / sub).glob('*.md'))
            if found:
                lines.append(f'### {kind}')
                for md in found:
                    fm = read_frontmatter(md)
                    lines.append(_entry(fm.get('name', md.stem), fm.get('description', ''), md))
                lines.append('')
    text = '\n'.join(line.rstrip() for line in lines)
    return text.rstrip('\n') + '\n'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description='Generate (or check) the AGENTS.md index.')
    parser.add_argument(
        '--check',
        action='store_true',
        help='exit 1 if the committed AGENTS.md differs from a fresh render',
    )
    args = parser.parse_args(argv)
    fresh = render()
    if args.check:
        current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.is_file() else ''
        if current != fresh:
            print(
                'AGENTS.md is stale or hand-edited — regenerate with '
                '`uv run --no-project -- python scripts/gen_agents_md.py`',
                file=sys.stderr,
            )
            return 1
        print('AGENTS.md is fresh')
        return 0
    OUTPUT.write_text(fresh, encoding='utf-8')
    print(f'wrote {OUTPUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
